name: Latest blog posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.3.5
        with:
          feed_list: "https://dev.to/feed/zachjonesnoel"
          commit_message: "Updated blog posts"
          committer_username: "zachjonesnoel-blog-bot"
          committer_email: "blog@zachjonesnoel.com"
          ##template: "[$title]($url)$newline$description"
          tag_post_pre_newline: "true"
